# Generated by Django 4.0 on 2021-12-15 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_supplier_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='store.position'),
        ),
    ]
